mysql:
  charset: utf8
  db: mega
  host: 127.0.0.1
  password: 123456
  user: root
mail:
  smtp: smtp.qq.com
  smtp-port: 25
  user: 592350960@qq.com
  password: teftuakyprosbfgd
server:
  url: http://127.0.0.1:8000